# Generated by Django 3.0 on 2023-01-01 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20230101_0844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentclassroom',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='core.Student'),
        ),
    ]
