# Generated by Django 3.0 on 2023-01-01 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20230101_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentclassroom',
            name='student',
            field=models.CharField(max_length=100),
        ),
    ]
