# Generated by Django 3.0 on 2023-01-05 14:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0009_testmany'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testmany',
            name='user',
            field=models.ManyToManyField(related_name='tm_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
