# Generated by Django 3.0 on 2023-01-05 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20230105_1543'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestMany',
        ),
    ]
