# Generated by Django 3.0 on 2023-01-07 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0015_remove_user_following'),
        ('core', '0011_delete_testmany'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
