# Generated by Django 3.0 on 2023-01-07 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_event_person_yearlyevent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yearlyevent',
            name='event',
        ),
        migrations.RemoveField(
            model_name='yearlyevent',
            name='person',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.DeleteModel(
            name='YearlyEvent',
        ),
    ]
