# Generated by Django 3.0 on 2023-01-08 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20230107_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='person',
            field=models.ManyToManyField(related_name='events', to='core.Person'),
        ),
    ]
